import type { Cook, Diner, Meal } from "./types";

// Static seed data standing in for a database. Neighborhoods are kept to a
// small London-ish set so proximity matching has something to chew on.

export const NEIGHBORHOODS = [
  "Peckham",
  "Hackney",
  "Brixton",
  "Camden",
  "Shoreditch",
  "Deptford",
] as const;

/** Rough adjacency so "nearby" scores above "across town". */
export const ADJACENCY: Record<string, string[]> = {
  Peckham: ["Deptford", "Brixton"],
  Deptford: ["Peckham"],
  Brixton: ["Peckham", "Camden"],
  Camden: ["Brixton", "Shoreditch"],
  Shoreditch: ["Hackney", "Camden"],
  Hackney: ["Shoreditch"],
};

export const COOKS: Cook[] = [
  {
    id: "cook-amara",
    name: "Amara Okafor",
    avatar: "👩🏾‍🍳",
    neighborhood: "Peckham",
    cuisines: ["ethiopian", "vegan-soul"],
    rating: 4.9,
    reviews: 212,
    bio: "Slow-cooked stews and injera made fresh every morning. Family recipes from Addis.",
    signatureDish: "Misir wot with hand-torn injera",
  },
  {
    id: "cook-luca",
    name: "Luca Bianchi",
    avatar: "👨🏻‍🍳",
    neighborhood: "Hackney",
    cuisines: ["italian"],
    rating: 4.7,
    reviews: 158,
    bio: "Nonna's Emilian pasta, rolled by hand. Small batches, big portions.",
    signatureDish: "Tortelli di zucca with sage butter",
  },
  {
    id: "cook-mei",
    name: "Mei Tanaka",
    avatar: "👩🏻‍🍳",
    neighborhood: "Shoreditch",
    cuisines: ["japanese", "korean"],
    rating: 4.8,
    reviews: 304,
    bio: "Izakaya-style sharing plates and a rotating donburi of the day.",
    signatureDish: "Karaage with yuzu kosho mayo",
  },
  {
    id: "cook-priya",
    name: "Priya Nair",
    avatar: "👩🏽‍🍳",
    neighborhood: "Brixton",
    cuisines: ["indian"],
    rating: 4.9,
    reviews: 271,
    bio: "Keralan home cooking — coconut, curry leaves, and a lot of love.",
    signatureDish: "Avial with red rice",
  },
  {
    id: "cook-sami",
    name: "Sami Haddad",
    avatar: "👨🏽‍🍳",
    neighborhood: "Camden",
    cuisines: ["lebanese"],
    rating: 4.6,
    reviews: 121,
    bio: "Mezze feasts built for a crowded table. Everything halal.",
    signatureDish: "Charcoal batata harra & muhammara",
  },
  {
    id: "cook-rosa",
    name: "Rosa Mendez",
    avatar: "👩🏽‍🍳",
    neighborhood: "Deptford",
    cuisines: ["mexican", "vegan-soul"],
    rating: 4.8,
    reviews: 189,
    bio: "Oaxacan comfort food. Masa nixtamalized in-house, salsas that bite back.",
    signatureDish: "Mole negro with heirloom tortillas",
  },
];

export const MEALS: Meal[] = [
  {
    id: "meal-misir",
    cookId: "cook-amara",
    title: "Beza Veg Feast",
    image: "🫕",
    description: "Misir wot, gomen, atkilt and shiro over a shared injera platter.",
    cuisine: "ethiopian",
    dietary: ["vegan", "vegetarian", "gluten-free", "dairy-free", "nut-free"],
    sitting: "early-dinner",
    neighborhood: "Peckham",
    price: 14,
    seatsTotal: 6,
    seatsTaken: ["diner-tomas", "diner-jade"],
    communal: true,
  },
  {
    id: "meal-tortelli",
    cookId: "cook-luca",
    title: "Hand-Rolled Tortelli Night",
    image: "🍝",
    description: "Tortelli di zucca, sage butter, aged parmigiano. Glass of lambrusco.",
    cuisine: "italian",
    dietary: ["vegetarian"],
    sitting: "late-dinner",
    neighborhood: "Hackney",
    price: 19,
    seatsTotal: 4,
    seatsTaken: ["diner-omar"],
    communal: true,
  },
  {
    id: "meal-donburi",
    cookId: "cook-mei",
    title: "Donburi of the Day",
    image: "🍲",
    description: "Chicken karaage donburi, miso soup, quick pickles. Solo-friendly.",
    cuisine: "japanese",
    dietary: ["dairy-free"],
    sitting: "lunch",
    neighborhood: "Shoreditch",
    price: 11,
    seatsTotal: 2,
    seatsTaken: [],
    communal: false,
  },
  {
    id: "meal-avial",
    cookId: "cook-priya",
    title: "Keralan Sadya Table",
    image: "🍛",
    description: "Avial, sambar, thoran, red rice and payasam on a banana leaf.",
    cuisine: "indian",
    dietary: ["vegetarian", "vegan", "gluten-free"],
    sitting: "early-dinner",
    neighborhood: "Brixton",
    price: 16,
    seatsTotal: 8,
    seatsTaken: ["diner-fatima", "diner-jade", "diner-nina"],
    communal: true,
  },
  {
    id: "meal-mezze",
    cookId: "cook-sami",
    title: "Late Mezze Spread",
    image: "🥙",
    description: "Twelve mezze, warm flatbread, charcoal veg. Halal, made to share.",
    cuisine: "lebanese",
    dietary: ["halal", "vegetarian"],
    sitting: "late-dinner",
    neighborhood: "Camden",
    price: 17,
    seatsTotal: 6,
    seatsTaken: ["diner-omar"],
    communal: true,
  },
  {
    id: "meal-mole",
    cookId: "cook-rosa",
    title: "Oaxacan Mole Supper",
    image: "🌮",
    description: "Mole negro, heirloom tortillas, charred greens, agua fresca.",
    cuisine: "mexican",
    dietary: ["gluten-free", "nut-free"],
    sitting: "early-dinner",
    neighborhood: "Deptford",
    price: 15,
    seatsTotal: 5,
    seatsTaken: ["diner-tomas"],
    communal: true,
  },
  {
    id: "meal-soul",
    cookId: "cook-rosa",
    title: "Vegan Soul Bowl",
    image: "🥗",
    description: "Smoked jackfruit, charred corn, black beans, cashew crema.",
    cuisine: "vegan-soul",
    dietary: ["vegan", "vegetarian", "dairy-free"],
    sitting: "lunch",
    neighborhood: "Deptford",
    price: 12,
    seatsTotal: 4,
    seatsTaken: [],
    communal: true,
  },
];

export const DINERS: Diner[] = [
  {
    id: "diner-tomas",
    name: "Tomás",
    avatar: "🧑🏻",
    neighborhood: "Peckham",
    tastes: ["ethiopian", "mexican", "vegan-soul"],
    dietary: ["vegetarian"],
    bio: "Will travel for stew. Always up for a long table.",
  },
  {
    id: "diner-jade",
    name: "Jade",
    avatar: "👩🏾",
    neighborhood: "Brixton",
    tastes: ["indian", "ethiopian", "thai"],
    dietary: ["vegan"],
    bio: "Spice tolerance: dangerously high.",
  },
  {
    id: "diner-omar",
    name: "Omar",
    avatar: "🧑🏽",
    neighborhood: "Camden",
    tastes: ["lebanese", "italian", "french"],
    dietary: ["halal"],
    bio: "Here for the mezze and the conversation.",
  },
  {
    id: "diner-fatima",
    name: "Fatima",
    avatar: "👩🏽",
    neighborhood: "Brixton",
    tastes: ["indian", "lebanese"],
    dietary: ["halal", "nut-free"],
    bio: "South London, south Indian, no notes.",
  },
  {
    id: "diner-nina",
    name: "Nina",
    avatar: "👩🏼",
    neighborhood: "Brixton",
    tastes: ["indian", "japanese", "korean"],
    dietary: ["gluten-free"],
    bio: "Donburi devotee, sadya curious.",
  },
  {
    id: "diner-kwame",
    name: "Kwame",
    avatar: "🧑🏿",
    neighborhood: "Deptford",
    tastes: ["mexican", "vegan-soul", "ethiopian"],
    dietary: ["vegan", "nut-free"],
    bio: "Plant-based and proud. Bring the salsa.",
  },
];

export function cookById(id: string): Cook | undefined {
  return COOKS.find((c) => c.id === id);
}

export function mealById(id: string): Meal | undefined {
  return MEALS.find((m) => m.id === id);
}

export function dinerById(id: string): Diner | undefined {
  return DINERS.find((d) => d.id === id);
}
